### ISSUE TITLE
go-raml-generator wish

### ISSUE THREAD

**Issue by ryanemax** [go-raml/raml#1]
I'm interested in RESTful API, and also Go Language.**Simple & Concurency.**

Can't help to image that there is a tool chains for auto build Full Stack RESTful Project, :P I'm very lazy.

I prefer to use Angularjs, Atom-shell, Ionic for Client(both pc & mobile) & Golang for Service

I don't admire Java, so will never use https://github.com/mulesoft/raml-for-jax-rs
# About RESTful Front-End

There is already a generator for [angularjs](http://restlet.com/),
and a generator for [js](https://github.com/mulesoft-labs/raml-generator).
It's not perfect but enough.
# About RESTful Back-End

I'm watching this project for a long time:
https://github.com/ant0ine/go-json-rest,A golang simple rest framework, with a nice "gorm", witch support "Migration", to generate database automaticly.
- need a generator for this framework
- or a good ORM embed within "go-raml"

**Comment by ryanemax** [comment]
I'm building the generator by myself, 

Project RAMLNova: https://github.com/anasinc/ramlnova.

This go-raml Parser is nice.

**Comment by advance512** [comment]
@ryanemax - would you be interested in helping with go-raml?
