### ISSUE TITLE
go-raml/raml - future development

### ISSUE THREAD

**Issue by advance512** [go-raml/raml#6]
Hi,

In the past year, I have come to accept that I currently do not have sufficient time to dedicate to go-raml/raml development. go-raml/raml is currently the most popular golang RAML parser in Github (and hence -  the world!! 😉). Mulesoft have shown interest in the project, possibly in assisting development or in sponsoring it. There's a lot of potential here.

I had a lot of fun working on it in the past and had big plans for it, including an implementation of the v1.0 spec, and the validator (which goes into validating traits, schemas and other 'by-name' references, JSON Schema and XML Schema, and more), and of course the many TODOs that litter the code. Oh, and naturally - an integration with a RESTful go library, and auto-generation of servers/clients. But then came entrepreneurial life.

This project deserves better, and as such I am looking for additional maintainers to assist or even take over. 

Please comment here if:
1. You are _currently_ interested in helping or taking over, 
2. You make use of go-raml/raml or know someone who uses this project in a production setting,
3. Can suggest potential maintainers or sponsors.

I am tagging various developers who showed interest in assisting with the project, or who forked it:
@jstoiko @arbrix @postatum @burrbd @buddhamagnet @elgris @stunti @prisamuel  @ryanemax @robvanmieghem @iwanbk @despiegk

Thanks and have a great day. :)

**Comment by eolexe** [comment]
Hey me and @elgris might be interested in taking over, we are building https://github.com/seesawlabs/apitest that should use both swagger and RAML

**Comment by robvanmieghem** [comment]
@advance512 We already built further on your code in https://github.com/Jumpscale/go-raml and added most of the 1.0 support, auto generation of servers/clients,.... 
Splitting the parser/validator out of that project is on our todo list (but not high prio for the moment)

**Comment by arbrix** [comment]
Hi. I'm interested in helping with improvements. It would be great to add RAML support to apitest as @eolexe mentioned above.

**Comment by advance512** [comment]
We've decided to focus go-raml/raml purely on being a parser/validator for RAML.

@arbrix will become a maintainer and join the go-raml organization.

**Comment by jstoiko** [comment]
I have been working with RAML 1.0 for a litttle while. I would love to see a parser in Go that supports RAML 1.0, especially types and libraries. Let me know if I can help in any way.
